stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Windows Build
build-windows:
  stage: build
  tags:
    - windows
  script:
    - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
    - qmake OpenRGB3DSpatialPlugin.pro
    - nmake release
  artifacts:
    paths:
      - release/OpenRGB3DSpatialPlugin.dll
    expire_in: 1 week
  only:
    - master
    - tags

# Linux Build
build-linux:
  stage: build
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y git build-essential qtbase5-dev qt5-qmake qtbase5-dev-tools libusb-1.0-0-dev libhidapi-dev
  script:
    - qmake OpenRGB3DSpatialPlugin.pro PREFIX=/usr
    - make -j$(nproc)
  artifacts:
    paths:
      - libOpenRGB3DSpatialPlugin.so
    expire_in: 1 week
  only:
    - master
    - tags

# macOS Build
build-macos:
  stage: build
  tags:
    - macos
  before_script:
    - brew install qt@5 hidapi libusb
    - export PATH="/usr/local/opt/qt@5/bin:$PATH"
  script:
    - qmake OpenRGB3DSpatialPlugin.pro
    - make -j8
  artifacts:
    paths:
      - libOpenRGB3DSpatialPlugin.dylib
    expire_in: 1 week
  only:
    - master
    - tags